
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

import styles from './page.module.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={styles.container} style={{margin:"0px", padding:"0px"}}>{children}</body>
    </html>
  )
}
